### ISSUE TITLE
Land not loading

### ISSUE THREAD

**Issue by Manliketjb** [MayhemStudios/FiveMReadyMaps#1]
walls and land not loading
![Screenshot 2022-10-26 111758](https://user-images.githubusercontent.com/82594996/198001823-ced65661-5876-4244-9ce4-2dd4333333ca.png)
![Screenshot 2022-10-26 111805](https://user-images.githubusercontent.com/82594996/198001835-30b6259d-f4fb-4ac9-8f4b-905fe66556be.png)

**Comment by MayhemStudios** [comment]
May I ask what map this may be?

**Comment by ElixerDevelopment** [comment]
Thanks for letting me know, unfortunately, some maps that are single-player are impossible to create to FiveM Ready cause some maps might stream an object, the FiveM is incapable of streaming. however, some maps stream objects that FiveM is incapable of streaming but it is less noticeable. However since it is streaming the walls, there is not much we can do about that.

The map will shortly be removed. 

Thank you.
