### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by SunnysTTV** [MayhemStudios/FiveMReadyMaps#2]
https://gta5-mods.com/maps/log-house

**Comment by ElixerDevelopment** [comment]
Thanks for suggesting this map, I will start working on the map, and seeing if it can be converted.

**Comment by ElixerDevelopment** [comment]
Unfortunately, The map is broken, The object the map uses for the floor, can't be streamed by FiveM, I am not able to add this map because it would be broken, with no way for you stand, and all objects inside would be floating in the air.

I have attached a screenshot of the issue. 
It just means that the creator of the map, has used an object, that FiveM can't stream from the original game files, there is nothing we can do to fix this issue, the only solution is if the map creator changes the floor object.
![image_2022-10-28_131812788](https://user-images.githubusercontent.com/55484272/198494432-dc486906-0ca5-4806-a2fa-8ffd963585eb.png)
